on:
  push:
    tags:
      - 'v*'

name: Build Project

jobs:
  build:
    name: Build Project
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish EXE files
        run: dotnet publish -p:PublishProfile=FolderProfile

      - name: Build Inno Setup installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: PC Timer Off.iss
          options: /O+

      - name: Rename executable
        run: mv "Output/PC Timer Off.exe" "Output/PC-Timer-Off-${{github.ref_name}}-x86.exe"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: Output/PC-Timer-Off-${{github.ref_name}}-x86.exe

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-installer

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ''
          files: ./PC-Timer-Off-${{github.ref_name}}-x86.exe
          fail_on_unmatched_files: true
          prerelease: ${{endsWith(github.ref_name, '-beta')}}
